### ISSUE TITLE
Repo maintenance: reusable action to setup NodeJS dependencies

### ISSUE THREAD

**Issue by marcalexiei** [Valerioageno/tuono#97]
Related to #96.

When working with the GitHub Actions workflows I noticed some issues:

## Setup `pnpm` via `npm i -g`

Some workflows setup `pnpm` using `npm i -g pnpm` rather than `pnpm/action-setup`.
I think we can always use `pnpm/action-setup` in conjunction with `setup-node` cache set to `pnpm` which might speed dependencies installation a little bit.

## `pnpm-lock.yaml` is not versioned

I noticed that `pnpm` lock file is ignored from versioning. 
IMHO this is a problem because someone (including CI tools) might install a version different from the one that other maintainers have installed and possibly fail unexpectedly. 
Besides this also prevents from using [`pnpm` `--frozen-lockfile`](https://pnpm.io/cli/install#--frozen-lockfile) which ensures that dependency specified in the lock files are installed.
I would consider removing it from the `.gitignore`

## `Node` and `pnpm` version are not aligned on development env and CI env

https://github.com/Valerioageno/tuono/blob/18a060e2bfcd20c06fb6dd6f9fe624a3a64b6b9c/package.json#L3

https://github.com/Valerioageno/tuono/blob/18a060e2bfcd20c06fb6dd6f9fe624a3a64b6b9c/.nvmrc#L1

While on workflows files a different version is used:

https://github.com/Valerioageno/tuono/blob/18a060e2bfcd20c06fb6dd6f9fe624a3a64b6b9c/.github/workflows/typescript.yml#L28

https://github.com/Valerioageno/tuono/blob/18a060e2bfcd20c06fb6dd6f9fe624a3a64b6b9c/.github/workflows/typescript.yml#L31

https://github.com/Valerioageno/tuono/blob/18a060e2bfcd20c06fb6dd6f9fe624a3a64b6b9c/.github/workflows/release.yml#L19-L23

## Possible solution to all above issues: reusable action for setup Node dependencies

Another improvement is to create a re-usable action to setup that reads configuration file to decide which tools version should be used:
- `setup-node` can detect the version from `.nvmrc`
- `pnpm/action-setup` already reads `package.json` `packageManager` field

<details>
<summary>Example of a setup nodeJS dependency action I'm using</summary>

```yml
name: Install Dependencies
description: This is a composite GitHub Action that sets up pnpm, node and installs the project's dependencies.

inputs:
  node-version:
    description: 'Explicit node version. Otherwise fallback reading `.nvmrc`'

runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js (via input)
      if: ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Setup Node.js (via .nvmrc)
      if: ${{ !inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Install Dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

```

Usage:

```yml
     - name: Install Dependencies
       uses: ./.github/actions/install-dependencies
```

</details>

---

> [!TIP]
> As always I'm willing to setup a PR with all proposed changes!
